"""Permutation-matching downstream task for all graph datasets.

Positive pairs are an original graph and an independently node-permuted copy;
negative pairs are two different graphs. The label is generated by the fixed
pair construction, not taken from domain metadata. A paired Transformer sees
the two token sequences with segment markers and predicts whether they encode
the same underlying graph.
"""

from __future__ import annotations

import argparse
import csv
import json
import random
from pathlib import Path

import torch
from sklearn.metrics import accuracy_score, balanced_accuracy_score, f1_score

from gptok2.data.io import load_records
from gptok2.canonical import canonicalize
from gptok2.data.schema_spec import SchemaSpec
from gptok2.data.schema import GraphRecord
from rps_gtok_consumption.data import TokenExample
from rps_gtok_consumption.training import TrainConfig, train_model
from rps_gtok_consumption.views import TokenViewBuilder
from gptok2_tokenizer import GPTok2Tokenizer
from scripts.run_topology_shift_downstream import permute_record, split_records


def pair_examples(records, builder, dataset, split, view, seed):
    rng=random.Random(seed); examples=[]
    for index, record in enumerate(records):
        permuted=permute_record(record, seed + index + 1000)
        same=builder.build(record,view); same_perm=builder.build(permuted,view)
        examples.append(TokenExample(graph_id=f"{record.graph_id}:positive",dataset=dataset,split=split,view=view,tokens=["PAIR_A",*same,"PAIR_B",*same_perm],y=1,task_type="classification",num_nodes=record.num_nodes,num_edges=int(record.edge_index.shape[1]) if record.edge_index.numel() else 0))
        other=records[(index+1)%len(records)]
        other_tokens=builder.build(other,view)
        examples.append(TokenExample(graph_id=f"{record.graph_id}:negative",dataset=dataset,split=split,view=view,tokens=["PAIR_A",*same,"PAIR_B",*other_tokens],y=0,task_type="classification",num_nodes=record.num_nodes,num_edges=int(record.edge_index.shape[1]) if record.edge_index.numel() else 0))
    rng.shuffle(examples); return examples


def main():
    parser=argparse.ArgumentParser(); parser.add_argument("--data-dir",default="rebuttal/data_21"); parser.add_argument("--dataset",required=True); parser.add_argument("--out",required=True); parser.add_argument("--views",nargs="+",default=["edge_list","canonical_edge_list","rps_gtok_plus"]); parser.add_argument("--max-graphs",type=int,default=60); parser.add_argument("--seeds",nargs="+",type=int,default=[2026,2027,2028]); parser.add_argument("--epochs",type=int,default=12); parser.add_argument("--batch-size",type=int,default=32); parser.add_argument("--max-len",type=int,default=512); parser.add_argument("--device",default="auto"); parser.add_argument("--canonical-max-search",type=int,default=10); parser.add_argument("--canonical-timeout-sec",type=float,default=.5); parser.add_argument("--exact-only",action="store_true")
    args=parser.parse_args(); records=load_records(Path(args.data_dir)/f"{args.dataset}.jsonl")[:args.max_graphs]; out=Path(args.out); out.mkdir(parents=True,exist_ok=True)
    if len(records)<12: raise SystemExit(f"{args.dataset}: too few graphs")
    splits=split_records(records)
    exact_counts={}
    if args.exact_only:
        spec=SchemaSpec(max_search_nodes=args.canonical_max_search,timeout_sec=args.canonical_timeout_sec)
        filtered={}
        for split,items in splits.items():
            kept=[]
            for index,record in enumerate(items):
                left=canonicalize(record,spec,exact=True,max_search_nodes=args.canonical_max_search,timeout_sec=args.canonical_timeout_sec)
                right=canonicalize(permute_record(record,987654+index),spec,exact=True,max_search_nodes=args.canonical_max_search,timeout_sec=args.canonical_timeout_sec)
                if left.exact_completed and right.exact_completed:
                    kept.append(record)
            filtered[split]=kept; exact_counts[split]=len(kept)
        splits=filtered
        if min(len(items) for items in splits.values()) < 3:
            raise SystemExit(f"{args.dataset}: exact-only subset too small: {exact_counts}")
    tokenizer=GPTok2Tokenizer({"canonicalization":{"max_search_nodes":args.canonical_max_search,"timeout_sec":args.canonical_timeout_sec}}).fit(splits["train"]); builder=TokenViewBuilder(tokenizer,seed=2026).fit(splits["train"],list(args.views)); rows=[]
    for view in args.views:
        materialized={split:pair_examples(items,builder,args.dataset,split,view,2026) for split,items in splits.items()}; union=[x.tokens for x in materialized["train"]]
        for seed in args.seeds:
            metrics=train_model(materialized,TrainConfig(max_len=args.max_len,batch_size=args.batch_size,epochs=args.epochs,patience=max(4,args.epochs//3),task_type="classification",model={"adapter":"plain","pair_aware":True,"dim":32,"layers":1,"heads":4,"dropout":.1},device=args.device,seed=seed,class_weight=True,vocab_sequences=union),out_dir=out/view/f"seed{seed}")
            test=metrics["test"]; rows.append({"dataset":args.dataset,"view":view,"seed":seed,"test_accuracy":test.get("accuracy"),"test_balanced_accuracy":test.get("balanced_accuracy"),"test_macro_f1":test.get("macro_f1"),"prediction_unique":test.get("prediction_unique"),"test_truncation_rate":metrics["sequence_audit"]["test"].get("truncation_rate"),"test_discarded_fraction":metrics["sequence_audit"]["test"].get("discarded_token_fraction"),"parameters":metrics["parameter_count"]})
    with (out/"results.csv").open("w",encoding="utf-8",newline="") as fh: writer=csv.DictWriter(fh,fieldnames=sorted({key for row in rows for key in row})); writer.writeheader(); writer.writerows(rows)
    (out/"protocol.json").write_text(json.dumps({"task":"permutation_matching_same_graph_vs_different_graph","dataset":args.dataset,"views":args.views,"seeds":args.seeds,"positive_pairs":"original_vs_node_permuted","negative_pairs":"different_graph","domain_labels_used":False,"exact_only":args.exact_only,"canonical_max_search":args.canonical_max_search,"canonical_timeout_sec":args.canonical_timeout_sec,"exact_counts":exact_counts},indent=2,sort_keys=True),encoding="utf-8")
    print(json.dumps({"dataset":args.dataset,"rows":len(rows)},indent=2))


if __name__=="__main__": main()
