"""Run the executable Phase-0 canonicalization and formal-contract audit."""

from __future__ import annotations

import argparse
import json
import random
from pathlib import Path

import networkx as nx

from gptok2.canonical import canonicalize
from gptok2.data.schema import graph_to_record
from gptok2.data.schema_spec import SchemaSpec


def main() -> None:
    parser = argparse.ArgumentParser(description="Run RPS-GTok Phase-0 audit.")
    parser.add_argument("--out", default="rebuttal/audits")
    parser.add_argument("--permutations", type=int, default=12)
    parser.add_argument("--max-search-nodes", type=int, default=100_000)
    args = parser.parse_args()

    root = Path(args.out)
    root.mkdir(parents=True, exist_ok=True)
    spec = SchemaSpec(
        name="phase0_topology",
        directed=False,
        multiedge=False,
        self_loop=False,
        retain_node_type=False,
        retain_node_attr=False,
        max_search_nodes=int(args.max_search_nodes),
    )
    rows = []
    for name, graph in adversarial_graphs().items():
        base = graph_to_record(graph, f"audit_{name}", family="audit")
        base_result = canonicalize(base, spec, exact=True, max_search_nodes=args.max_search_nodes)
        stable = 0
        for seed in range(int(args.permutations)):
            permuted = permute_graph(graph, seed)
            record = graph_to_record(permuted, f"audit_{name}", family="audit")
            result = canonicalize(record, spec, exact=True, max_search_nodes=args.max_search_nodes)
            stable += int(result.canonical_key == base_result.canonical_key)
        rows.append(
            {
                "graph": name,
                "nodes": int(graph.number_of_nodes()),
                "edges": int(graph.number_of_edges()),
                "tie_groups": [len(x) for x in base_result.tie_groups],
                "refinement_rounds": base_result.refinement_rounds,
                "search_nodes": base_result.search_nodes,
                "search_branches": base_result.search_branches,
                "exact_completed": base_result.exact_completed,
                "fallback_used": base_result.fallback_used,
                "stability_rate": stable / max(1, int(args.permutations)),
                "canonicalization_sec": base_result.elapsed_sec,
            }
        )

    (root / "canonicalization_audit.json").write_text(json.dumps(rows, indent=2), encoding="utf-8")
    write_canonical_report(root / "canonicalization_audit.md", rows, args)
    write_formal_report(root / "formal_claim_audit.md")
    write_schema_report(root / "schema_audit.md")
    print(json.dumps({"graphs": len(rows), "out": str(root)}, indent=2))


def adversarial_graphs() -> dict[str, nx.Graph]:
    return {
        "isolated_nodes": nx.empty_graph(6),
        "cycle": nx.cycle_graph(8),
        "complete": nx.complete_graph(6),
        "regular": nx.random_regular_graph(3, 10, seed=7),
        "star": nx.star_graph(8),
        "bipartite": nx.complete_bipartite_graph(4, 4),
        "repeated_motif": nx.disjoint_union_all([nx.cycle_graph(4), nx.cycle_graph(4)]),
        "sparse_path": nx.path_graph(20),
    }


def permute_graph(graph: nx.Graph, seed: int) -> nx.Graph:
    nodes = list(graph.nodes())
    random.Random(seed).shuffle(nodes)
    mapping = {old: new for new, old in enumerate(nodes)}
    return nx.relabel_nodes(graph, mapping, copy=True)


def write_canonical_report(path: Path, rows: list[dict], args: argparse.Namespace) -> None:
    lines = [
        "# Canonicalization audit",
        "",
        "This report is generated by scripts/run_phase0_audit.py.",
        "",
        f"- permutation trials: {args.permutations}",
        f"- search-node budget: {args.max_search_nodes}",
        "- schema: phase0_topology",
        "",
        "| Graph | Nodes | Edges | Tie groups | Search nodes | Exact | Fallback | Stability |",
        "| --- | ---: | ---: | --- | ---: | :---: | :---: | ---: |",
    ]
    for row in rows:
        lines.append(
            "| {graph} | {nodes} | {edges} | {tie_groups} | {search_nodes} | {exact_completed} | {fallback_used} | {stability_rate:.3f} |".format(
                **row
            )
        )
    lines += [
        "",
        "The exact guarantee is conditional on exact_completed=True. A non-zero fallback rate is not silently treated as a theorem-level permutation guarantee.",
    ]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_formal_report(path: Path) -> None:
    path.write_text(
        "\n".join(
            [
                "# Formal claim audit",
                "",
                "## Current implementation contract",
                "",
                "- Primitive program execution is implemented by gptok2/program/interpreter.py.",
                "- The canonicalization entry point is gptok2/canonical.py.",
                "- The canonicalizer reports exact completion, search branches and fallback use.",
                "- structure_fidelity now reports strict_topology_exact, while full schema-aware attribute scoring remains a follow-up.",
                "",
                "## Claim status",
                "",
                "| Claim | Current audit status | Required follow-up |",
                "| --- | --- | --- |",
                "| Primitive program reconstructs retained schema | partial | add strict schema-aware interpreter audit |",
                "| Strict topology equality | implemented | run full dataset audit |",
                "| Expansion equals original primitive sequence | unproven | test Unemitted and fragment ordering |",
                "| Interpreted graph-state equivalence | target invariant | add adversarial tests |",
                "| Permutation stability | conditional | require exact_completed and run dataset audit |",
                "| Identifier-only autoregressive generation is lossless | not claimed | add payload generator before making claim |",
            ]
        )
        + "\n",
        encoding="utf-8",
    )


def write_schema_report(path: Path) -> None:
    path.write_text(
        "\n".join(
            [
                "# Schema audit",
                "",
                "The executable schema source is configs/schema_manifest.yaml.",
                "",
                "The current release audit uses an explicit topology contract. Attribute, directed, multiedge and self-loop contracts require corresponding loader and interpreter support before being counted as reconstructed.",
            ]
        )
        + "\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
